# Generated by Django 5.2.5 on 2026-02-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavebalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.IntegerField(default=12, help_text='Number of casual leave days available per year.'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='emergency_leave',
            field=models.IntegerField(default=5, help_text='Number of emergency leave days available per year.'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.OneToOneField(help_text='Employee to whom this leave balance belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.IntegerField(default=10, help_text='Number of sick leave days available per year.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='action_by',
            field=models.ForeignKey(blank=True, help_text='Manager or admin who approved or rejected the leave.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='action_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the leave was approved or rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the leave was applied.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(help_text='Employee requesting the leave.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(help_text='End date of the leave.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave')], default='CASUAL', help_text='Type of leave being requested.', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(help_text='Reason for applying for leave.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(help_text='Start date of the leave.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the leave request.', max_length=20),
        ),
    ]
