# Generated by Django 5.2.5 on 2026-03-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leavebalance_casual_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration_type',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day'), ('HOURLY', 'Hourly Permission')], default='FULL_DAY', help_text='Duration of the leave.', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='from_time',
            field=models.TimeField(blank=True, help_text='Start time (if hourly permission).', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_time',
            field=models.TimeField(blank=True, help_text='End time (if hourly permission).', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Total hours calculated for this leave.', max_digits=4),
        ),
    ]
