# Generated by Django 5.2.5 on 2026-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaverequest_duration_type_leaverequest_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Number of casual leave days available per year.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='emergency_leave',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Number of emergency leave days available per year.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Number of sick leave days available per year.', max_digits=5),
        ),
    ]
