# Generated by Django 5.2.5 on 2026-02-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_blood_group_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pictures/'),
        ),
    ]
