# Generated by Django 5.2.5 on 2026-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, help_text="Employee's current city or place.", max_length=100, null=True),
        ),
    ]
