# Generated by Django 5.2.5 on 2026-03-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
    ]
