# Generated by Django 5.2.5 on 2026-03-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Indicates whether the user account has been rejected by an admin.'),
        ),
    ]
