# Generated by Django 5.2.5 on 2026-02-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL', unique=True)),
                ('p256dh', models.CharField(help_text='Diffie-Hellman public key (base64)', max_length=500)),
                ('auth', models.CharField(help_text='Authentication token (base64)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this subscription was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time')),
                ('user_agent', models.CharField(blank=True, help_text='User agent of the browser that subscribed', max_length=500, null=True)),
                ('user', models.ForeignKey(help_text='User who subscribed to push notifications', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Push Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
