# Generated by Django 5.2.5 on 2026-02-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, help_text='Time when the employee checked in.', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, help_text='Time when the employee checked out.', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Date for which this attendance record applies.'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(help_text='Employee whose attendance is being recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
